[profile.default]
solc_version   = '0.8.21'
optimizer      = true
optimizer_runs = 200

fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read-write", path = "./script/output/"}
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
